// Copyright 2024 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.
#ifndef EVK_XU316_PORTS_H
#define EVK_XU316_PORTS_H
#include <platform.h>  // for tile identifiers
#include "../boards_utils.h"


#define PORT_SQI_CS_TILE_NUM 0
#define PORT_SQI_CS_TILE tile[PORT_SQI_CS_TILE_NUM]
#define PORT_SQI_SCLK_TILE_NUM 0
#define PORT_SQI_SCLK_TILE tile[PORT_SQI_SCLK_TILE_NUM]
#define PORT_SQI_SIO_TILE_NUM 0
#define PORT_SQI_SIO_TILE tile[PORT_SQI_SIO_TILE_NUM]
#define PORT_LEDS_TILE_NUM 0
#define PORT_LEDS_TILE tile[PORT_LEDS_TILE_NUM]
#define PORT_BUTTONS_TILE_NUM 0
#define PORT_BUTTONS_TILE tile[PORT_BUTTONS_TILE_NUM]
#define WIFI_WIRQ_TILE_NUM 0
#define WIFI_WIRQ_TILE tile[WIFI_WIRQ_TILE_NUM]
#define WIFI_MOSI_TILE_NUM 0
#define WIFI_MOSI_TILE tile[WIFI_MOSI_TILE_NUM]
#define WIFI_WUP_RST_N_TILE_NUM 0
#define WIFI_WUP_RST_N_TILE tile[WIFI_WUP_RST_N_TILE_NUM]
#define WIFI_CS_N_TILE_NUM 0
#define WIFI_CS_N_TILE tile[WIFI_CS_N_TILE_NUM]
#define WIFI_CLK_TILE_NUM 0
#define WIFI_CLK_TILE tile[WIFI_CLK_TILE_NUM]
#define WIFI_MISO_TILE_NUM 0
#define WIFI_MISO_TILE tile[WIFI_MISO_TILE_NUM]
#define PORT_PDM_CLK_TILE_NUM 1
#define PORT_PDM_CLK_TILE tile[PORT_PDM_CLK_TILE_NUM]
#define PORT_PDM_DATA_TILE_NUM 1
#define PORT_PDM_DATA_TILE tile[PORT_PDM_DATA_TILE_NUM]
#define PORT_MCLK_IN_TILE_NUM 1
#define PORT_MCLK_IN_TILE tile[PORT_MCLK_IN_TILE_NUM]
#define PORT_I2S_BCLK_TILE_NUM 1
#define PORT_I2S_BCLK_TILE tile[PORT_I2S_BCLK_TILE_NUM]
#define PORT_I2S_LRCLK_TILE_NUM 1
#define PORT_I2S_LRCLK_TILE tile[PORT_I2S_LRCLK_TILE_NUM]
#define PORT_I2S_DAC_DATA_TILE_NUM 1
#define PORT_I2S_DAC_DATA_TILE tile[PORT_I2S_DAC_DATA_TILE_NUM]
#define PORT_I2S_ADC_DATA_TILE_NUM 1
#define PORT_I2S_ADC_DATA_TILE tile[PORT_I2S_ADC_DATA_TILE_NUM]
#define PORT_CODEC_RST_N_TILE_NUM 1
#define PORT_CODEC_RST_N_TILE tile[PORT_CODEC_RST_N_TILE_NUM]


#define PORT_SQI_CS BOARDS_PORT(PORT_SQI_CS_TILE_NUM, 1B)
#define PORT_SQI_SCLK BOARDS_PORT(PORT_SQI_SCLK_TILE_NUM, 1C)
#define PORT_SQI_SIO BOARDS_PORT(PORT_SQI_SIO_TILE_NUM, 4B)
#define PORT_LEDS BOARDS_PORT(PORT_LEDS_TILE_NUM, 4C)
#define PORT_BUTTONS BOARDS_PORT(PORT_BUTTONS_TILE_NUM, 4D)
#define WIFI_WIRQ BOARDS_PORT(WIFI_WIRQ_TILE_NUM, 1I)
#define WIFI_MOSI BOARDS_PORT(WIFI_MOSI_TILE_NUM, 1J)
#define WIFI_WUP_RST_N BOARDS_PORT(WIFI_WUP_RST_N_TILE_NUM, 4E)
#define WIFI_CS_N BOARDS_PORT(WIFI_CS_N_TILE_NUM, 4F)
#define WIFI_CLK BOARDS_PORT(WIFI_CLK_TILE_NUM, 1L)
#define WIFI_MISO BOARDS_PORT(WIFI_MISO_TILE_NUM, 1M)
#define PORT_PDM_CLK BOARDS_PORT(PORT_PDM_CLK_TILE_NUM, 1G)
#define PORT_PDM_DATA BOARDS_PORT(PORT_PDM_DATA_TILE_NUM, 1F)
#define PORT_MCLK_IN BOARDS_PORT(PORT_MCLK_IN_TILE_NUM, 1D)
#define PORT_I2S_BCLK BOARDS_PORT(PORT_I2S_BCLK_TILE_NUM, 1C)
#define PORT_I2S_LRCLK BOARDS_PORT(PORT_I2S_LRCLK_TILE_NUM, 1B)
#define PORT_I2S_DAC_DATA BOARDS_PORT(PORT_I2S_DAC_DATA_TILE_NUM, 1A)
#define PORT_I2S_ADC_DATA BOARDS_PORT(PORT_I2S_ADC_DATA_TILE_NUM, 1N)
#define PORT_CODEC_RST_N BOARDS_PORT(PORT_CODEC_RST_N_TILE_NUM, 4A)


void xk_evk_xu316_init_ports();

#endif /* EVK_XU316_PORTS_H */

