// Copyright 2024 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.
#ifndef AUDIO_216_MC_AB_PORTS_H
#define AUDIO_216_MC_AB_PORTS_H

#include "../boards_utils.h"
#include <platform.h>

#define PORT_SQI_CS BOARDS_PORT(PORT_SQI_CS_TILE_NUM, 1B)
#define PORT_SQI_SCLK BOARDS_PORT(PORT_SQI_SCLK_TILE_NUM, 1C)
#define PORT_SQI_SIO BOARDS_PORT(PORT_SQI_SIO_TILE_NUM, 4B)
#define PORT_PLL_REF BOARDS_PORT(PORT_PLL_REF_TILE_NUM, 1A)
#define PORT_MCLK_IN BOARDS_PORT(PORT_MCLK_IN_TILE_NUM, 1F)
#define PORT_I2S_LRCLK BOARDS_PORT(PORT_I2S_LRCLK_TILE_NUM, 1G)
#define PORT_I2S_BCLK BOARDS_PORT(PORT_I2S_BCLK_TILE_NUM, 1H)
#define PORT_I2S_DAC0 BOARDS_PORT(PORT_I2S_DAC0_TILE_NUM, 1M)
#define PORT_I2S_DAC1 BOARDS_PORT(PORT_I2S_DAC1_TILE_NUM, 1N)
#define PORT_I2S_DAC2 BOARDS_PORT(PORT_I2S_DAC2_TILE_NUM, 1O)
#define PORT_I2S_DAC3 BOARDS_PORT(PORT_I2S_DAC3_TILE_NUM, 1P)
#define PORT_I2S_ADC0 BOARDS_PORT(PORT_I2S_ADC0_TILE_NUM, 1I)
#define PORT_I2S_ADC1 BOARDS_PORT(PORT_I2S_ADC1_TILE_NUM, 1J)
#define PORT_I2S_ADC2 BOARDS_PORT(PORT_I2S_ADC2_TILE_NUM, 1K)
#define PORT_I2S_ADC3 BOARDS_PORT(PORT_I2S_ADC3_TILE_NUM, 1L)
#define PORT_I2C BOARDS_PORT(PORT_I2C_TILE_NUM, 4A)
#define PORT_DSD_DAC0 BOARDS_PORT(PORT_DSD_DAC0_TILE_NUM, 1M)
#define PORT_DSD_DAC1 BOARDS_PORT(PORT_DSD_DAC1_TILE_NUM, 1N)
#define PORT_DSD_CLK BOARDS_PORT(PORT_DSD_CLK_TILE_NUM, 1G)
#define PORT_ADAT_OUT BOARDS_PORT(PORT_ADAT_OUT_TILE_NUM, 1E)
#define PORT_SPDIF_OUT BOARDS_PORT(PORT_SPDIF_OUT_TILE_NUM, 1D)
#define PORT_USB_TX_READYIN BOARDS_PORT(PORT_USB_TX_READYIN_TILE_NUM, 1H)
#define PORT_USB_CLK BOARDS_PORT(PORT_USB_CLK_TILE_NUM, 1J)
#define PORT_USB_TX_READYOUT BOARDS_PORT(PORT_USB_TX_READYOUT_TILE_NUM, 1K)
#define PORT_USB_RX_READY BOARDS_PORT(PORT_USB_RX_READY_TILE_NUM, 1I)
#define PORT_USB_FLAG0 BOARDS_PORT(PORT_USB_FLAG0_TILE_NUM, 1E)
#define PORT_USB_FLAG1 BOARDS_PORT(PORT_USB_FLAG1_TILE_NUM, 1F)
#define PORT_USB_FLAG2 BOARDS_PORT(PORT_USB_FLAG2_TILE_NUM, 1G)
#define PORT_USB_TXD BOARDS_PORT(PORT_USB_TXD_TILE_NUM, 8A)
#define PORT_USB_RXD BOARDS_PORT(PORT_USB_RXD_TILE_NUM, 8B)
#define PORT_MCLK_COUNT BOARDS_PORT(PORT_MCLK_COUNT_TILE_NUM, 16B)
#define PORT_MCLK_IN_USB BOARDS_PORT(PORT_MCLK_IN_USB_TILE_NUM, 1L)
#define PORT_MIDI_IN BOARDS_PORT(PORT_MIDI_IN_TILE_NUM, 1M)
#define PORT_MIDI_OUT BOARDS_PORT(PORT_MIDI_OUT_TILE_NUM, 1N)
#define PORT_ADAT_IN BOARDS_PORT(PORT_ADAT_IN_TILE_NUM, 1O)
#define PORT_SPDIF_IN BOARDS_PORT(PORT_SPDIF_IN_TILE_NUM, 1P)

#define PORT_SQI_CS_TILE tile[PORT_SQI_CS_TILE_NUM]
#define PORT_SQI_CS_TILE_NUM 0
#define PORT_SQI_SCLK_TILE tile[PORT_SQI_SCLK_TILE_NUM]
#define PORT_SQI_SCLK_TILE_NUM 0
#define PORT_SQI_SIO_TILE tile[PORT_SQI_SIO_TILE_NUM]
#define PORT_SQI_SIO_TILE_NUM 0
#define PORT_PLL_REF_TILE tile[PORT_PLL_REF_TILE_NUM]
#define PORT_PLL_REF_TILE_NUM 0
#define PORT_MCLK_IN_TILE tile[PORT_MCLK_IN_TILE_NUM]
#define PORT_MCLK_IN_TILE_NUM 0
#define PORT_I2S_LRCLK_TILE tile[PORT_I2S_LRCLK_TILE_NUM]
#define PORT_I2S_LRCLK_TILE_NUM 0
#define PORT_I2S_BCLK_TILE tile[PORT_I2S_BCLK_TILE_NUM]
#define PORT_I2S_BCLK_TILE_NUM 0
#define PORT_I2S_DAC0_TILE tile[PORT_I2S_DAC0_TILE_NUM]
#define PORT_I2S_DAC0_TILE_NUM 0
#define PORT_I2S_DAC1_TILE tile[PORT_I2S_DAC1_TILE_NUM]
#define PORT_I2S_DAC1_TILE_NUM 0
#define PORT_I2S_DAC2_TILE tile[PORT_I2S_DAC2_TILE_NUM]
#define PORT_I2S_DAC2_TILE_NUM 0
#define PORT_I2S_DAC3_TILE tile[PORT_I2S_DAC3_TILE_NUM]
#define PORT_I2S_DAC3_TILE_NUM 0
#define PORT_I2S_ADC0_TILE tile[PORT_I2S_ADC0_TILE_NUM]
#define PORT_I2S_ADC0_TILE_NUM 0
#define PORT_I2S_ADC1_TILE tile[PORT_I2S_ADC1_TILE_NUM]
#define PORT_I2S_ADC1_TILE_NUM 0
#define PORT_I2S_ADC2_TILE tile[PORT_I2S_ADC2_TILE_NUM]
#define PORT_I2S_ADC2_TILE_NUM 0
#define PORT_I2S_ADC3_TILE tile[PORT_I2S_ADC3_TILE_NUM]
#define PORT_I2S_ADC3_TILE_NUM 0
#define PORT_I2C_TILE tile[PORT_I2C_TILE_NUM]
#define PORT_I2C_TILE_NUM 0
#define PORT_DSD_DAC0_TILE tile[PORT_DSD_DAC0_TILE_NUM]
#define PORT_DSD_DAC0_TILE_NUM 0
#define PORT_DSD_DAC1_TILE tile[PORT_DSD_DAC1_TILE_NUM]
#define PORT_DSD_DAC1_TILE_NUM 0
#define PORT_DSD_CLK_TILE tile[PORT_DSD_CLK_TILE_NUM]
#define PORT_DSD_CLK_TILE_NUM 0
#define PORT_ADAT_OUT_TILE tile[PORT_ADAT_OUT_TILE_NUM]
#define PORT_ADAT_OUT_TILE_NUM 0
#define PORT_SPDIF_OUT_TILE tile[PORT_SPDIF_OUT_TILE_NUM]
#define PORT_SPDIF_OUT_TILE_NUM 0
#define PORT_USB_TX_READYIN_TILE tile[PORT_USB_TX_READYIN_TILE_NUM]
#define PORT_USB_TX_READYIN_TILE_NUM 1
#define PORT_USB_CLK_TILE tile[PORT_USB_CLK_TILE_NUM]
#define PORT_USB_CLK_TILE_NUM 1
#define PORT_USB_TX_READYOUT_TILE tile[PORT_USB_TX_READYOUT_TILE_NUM]
#define PORT_USB_TX_READYOUT_TILE_NUM 1
#define PORT_USB_RX_READY_TILE tile[PORT_USB_RX_READY_TILE_NUM]
#define PORT_USB_RX_READY_TILE_NUM 1
#define PORT_USB_FLAG0_TILE tile[PORT_USB_FLAG0_TILE_NUM]
#define PORT_USB_FLAG0_TILE_NUM 1
#define PORT_USB_FLAG1_TILE tile[PORT_USB_FLAG1_TILE_NUM]
#define PORT_USB_FLAG1_TILE_NUM 1
#define PORT_USB_FLAG2_TILE tile[PORT_USB_FLAG2_TILE_NUM]
#define PORT_USB_FLAG2_TILE_NUM 1
#define PORT_USB_TXD_TILE tile[PORT_USB_TXD_TILE_NUM]
#define PORT_USB_TXD_TILE_NUM 1
#define PORT_USB_RXD_TILE tile[PORT_USB_RXD_TILE_NUM]
#define PORT_USB_RXD_TILE_NUM 1
#define PORT_MCLK_COUNT_TILE tile[PORT_MCLK_COUNT_TILE_NUM]
#define PORT_MCLK_COUNT_TILE_NUM 1
#define PORT_MCLK_IN_USB_TILE tile[PORT_MCLK_IN_USB_TILE_NUM]
#define PORT_MCLK_IN_USB_TILE_NUM 1
#define PORT_MIDI_IN_TILE tile[PORT_MIDI_IN_TILE_NUM]
#define PORT_MIDI_IN_TILE_NUM 1
#define PORT_MIDI_OUT_TILE tile[PORT_MIDI_OUT_TILE_NUM]
#define PORT_MIDI_OUT_TILE_NUM 1
#define PORT_ADAT_IN_TILE tile[PORT_ADAT_IN_TILE_NUM]
#define PORT_ADAT_IN_TILE_NUM 1
#define PORT_SPDIF_IN_TILE tile[PORT_SPDIF_IN_TILE_NUM]
#define PORT_SPDIF_IN_TILE_NUM 1


#ifndef XCORE_200_MC_AUDIO_HW_VERSION
#define XCORE_200_MC_AUDIO_HW_VERSION 2
#endif


#if XCORE_200_MC_AUDIO_HW_VERSION == 2

/* General output port bit definitions */
#define P_GPIO_DSD_MODE         (1 << 0) /* DSD mode select 0 = 8i/8o I2S, 1 = 8o DSD*/
#define P_GPIO_DAC_RST_N        (1 << 1)
#define P_GPIO_USB_SEL0         (1 << 2)
#define P_GPIO_USB_SEL1         (1 << 3)
#define P_GPIO_VBUS_EN          (1 << 4)
#define P_GPIO_PLL_SEL          (1 << 5) /* 1 = CS2100, 0 = Phaselink clock source */
#define P_GPIO_ADC_RST_N        (1 << 6)
#define P_GPIO_MCLK_FSEL        (1 << 7) /* Select frequency on Phaselink clock. 0 = 24.576MHz for 48k, 1 = 22.5792MHz for 44.1k.*/

#else

/* General output port bit definitions */
#define P_GPIO_DSD_MODE         (1 << 0) /* DSD mode select 0 = 8i/8o I2S, 1 = 8o DSD*/
#define P_GPIO_DAC_RST_N        (1 << 1)
#define P_GPIO_ADC_RST_N        (1 << 2)
#define P_GPIO_USB_SEL0         (1 << 3)
#define P_GPIO_USB_SEL1         (1 << 4)
#define P_GPIO_VBUS_EN          (1 << 5)
#define P_GPIO_MCLK_FSEL        (1 << 6) /* Select frequency on Phaselink clock. 0 = 24.576MHz for 48k, 1 = 22.5792MHz for 44.1k.*/
#define P_GPIO_PLL_SEL          (1 << 7) /* 1 = CS2100, 0 = Phaselink clock source */

#endif


/*LED array defines*/
#define LED_ALL_ON              0xf00f
#define LED_SQUARE_BIG          0x9009
#define LED_SQUARE_SML          0x6006
#define LED_ROW_1               0xf001
#define LED_ROW_2               0xf003
#define LED_ROW_3               0xf007
#define ALL_OFF                 0x0000
// LED array masks
#define LED_MASK_COL_OFF        0x7fff
#define LED_MASK_DISABLE        0xffff




#endif /* AUDIO_216_MC_AB_PORTS_H */

