// Copyright 2024 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.
#ifndef AUDIO_316_MC_AB_PORTS_H
#define AUDIO_316_MC_AB_PORTS_H

#include "../boards_utils.h"

#include <platform.h>  // for tile identifiers

#define PORT_SQI_CS BOARDS_PORT(PORT_SQI_CS_TILE_NUM, 1B)
#define PORT_SQI_SCLK BOARDS_PORT(PORT_SQI_SCLK_TILE_NUM, 1C)
#define PORT_SQI_SIO BOARDS_PORT(PORT_SQI_SIO_TILE_NUM, 4B)
#define PORT_CTRL BOARDS_PORT(PORT_CTRL_TILE_NUM, 8D)
#define PORT_I2C_SCL BOARDS_PORT(PORT_I2C_SCL_TILE_NUM, 1L)
#define PORT_I2C_SDA BOARDS_PORT(PORT_I2C_SDA_TILE_NUM, 1M)
#define PORT_MCLK_COUNT BOARDS_PORT(PORT_MCLK_COUNT_TILE_NUM, 16B)
#define PORT_MCLK_IN_USB BOARDS_PORT(PORT_MCLK_IN_USB_TILE_NUM, 1D)
#define PORT_PLL_REF BOARDS_PORT(PORT_PLL_REF_TILE_NUM, 1A)
#define PORT_ADAT_IN BOARDS_PORT(PORT_ADAT_IN_TILE_NUM, 1O)
#define PORT_SPDIF_IN BOARDS_PORT(PORT_SPDIF_IN_TILE_NUM, 1N)
#define PORT_MCLK_IN BOARDS_PORT(PORT_MCLK_IN_TILE_NUM, 1D)
#define PORT_MCLK_COUNT_2 BOARDS_PORT(PORT_MCLK_COUNT_2_TILE_NUM, 16B)
#define PORT_I2S_LRCLK BOARDS_PORT(PORT_I2S_LRCLK_TILE_NUM, 1B)
#define PORT_I2S_BCLK BOARDS_PORT(PORT_I2S_BCLK_TILE_NUM, 1C)
#define PORT_I2S_DAC0 BOARDS_PORT(PORT_I2S_DAC0_TILE_NUM, 1P)
#define PORT_I2S_DAC1 BOARDS_PORT(PORT_I2S_DAC1_TILE_NUM, 1O)
#define PORT_I2S_DAC2 BOARDS_PORT(PORT_I2S_DAC2_TILE_NUM, 1N)
#define PORT_I2S_DAC3 BOARDS_PORT(PORT_I2S_DAC3_TILE_NUM, 1M)
#define PORT_I2S_ADC0 BOARDS_PORT(PORT_I2S_ADC0_TILE_NUM, 1I)
#define PORT_I2S_ADC1 BOARDS_PORT(PORT_I2S_ADC1_TILE_NUM, 1J)
#define PORT_I2S_ADC2 BOARDS_PORT(PORT_I2S_ADC2_TILE_NUM, 1K)
#define PORT_I2S_ADC3 BOARDS_PORT(PORT_I2S_ADC3_TILE_NUM, 1L)
#define PORT_ADAT_OUT BOARDS_PORT(PORT_ADAT_OUT_TILE_NUM, 1G)
#define PORT_SPDIF_OUT BOARDS_PORT(PORT_SPDIF_OUT_TILE_NUM, 1A)
#define PORT_MIDI_IN BOARDS_PORT(PORT_MIDI_IN_TILE_NUM, 1F)
#define PORT_MIDI_OUT BOARDS_PORT(PORT_MIDI_OUT_TILE_NUM, 4C)

#define PORT_SQI_CS_TILE tile[PORT_SQI_CS_TILE_NUM]
#define PORT_SQI_CS_TILE_NUM 0
#define PORT_SQI_SCLK_TILE tile[PORT_SQI_SCLK_TILE_NUM]
#define PORT_SQI_SCLK_TILE_NUM 0
#define PORT_SQI_SIO_TILE tile[PORT_SQI_SIO_TILE_NUM]
#define PORT_SQI_SIO_TILE_NUM 0
#define PORT_CTRL_TILE tile[PORT_CTRL_TILE_NUM]
#define PORT_CTRL_TILE_NUM 0
#define PORT_I2C_SCL_TILE tile[PORT_I2C_SCL_TILE_NUM]
#define PORT_I2C_SCL_TILE_NUM 0
#define PORT_I2C_SDA_TILE tile[PORT_I2C_SDA_TILE_NUM]
#define PORT_I2C_SDA_TILE_NUM 0
#define PORT_MCLK_COUNT_TILE tile[PORT_MCLK_COUNT_TILE_NUM]
#define PORT_MCLK_COUNT_TILE_NUM 0
#define PORT_MCLK_IN_USB_TILE tile[PORT_MCLK_IN_USB_TILE_NUM]
#define PORT_MCLK_IN_USB_TILE_NUM 0
#define PORT_PLL_REF_TILE tile[PORT_PLL_REF_TILE_NUM]
#define PORT_PLL_REF_TILE_NUM 0
#define PORT_ADAT_IN_TILE tile[PORT_ADAT_IN_TILE_NUM]
#define PORT_ADAT_IN_TILE_NUM 0
#define PORT_SPDIF_IN_TILE tile[PORT_SPDIF_IN_TILE_NUM]
#define PORT_SPDIF_IN_TILE_NUM 0
#define PORT_MCLK_IN_TILE tile[PORT_MCLK_IN_TILE_NUM]
#define PORT_MCLK_IN_TILE_NUM 1
#define PORT_MCLK_COUNT_2_TILE tile[PORT_MCLK_COUNT_2_TILE_NUM]
#define PORT_MCLK_COUNT_2_TILE_NUM 1
#define PORT_I2S_LRCLK_TILE tile[PORT_I2S_LRCLK_TILE_NUM]
#define PORT_I2S_LRCLK_TILE_NUM 1
#define PORT_I2S_BCLK_TILE tile[PORT_I2S_BCLK_TILE_NUM]
#define PORT_I2S_BCLK_TILE_NUM 1
#define PORT_I2S_DAC0_TILE tile[PORT_I2S_DAC0_TILE_NUM]
#define PORT_I2S_DAC0_TILE_NUM 1
#define PORT_I2S_DAC1_TILE tile[PORT_I2S_DAC1_TILE_NUM]
#define PORT_I2S_DAC1_TILE_NUM 1
#define PORT_I2S_DAC2_TILE tile[PORT_I2S_DAC2_TILE_NUM]
#define PORT_I2S_DAC2_TILE_NUM 1
#define PORT_I2S_DAC3_TILE tile[PORT_I2S_DAC3_TILE_NUM]
#define PORT_I2S_DAC3_TILE_NUM 1
#define PORT_I2S_ADC0_TILE tile[PORT_I2S_ADC0_TILE_NUM]
#define PORT_I2S_ADC0_TILE_NUM 1
#define PORT_I2S_ADC1_TILE tile[PORT_I2S_ADC1_TILE_NUM]
#define PORT_I2S_ADC1_TILE_NUM 1
#define PORT_I2S_ADC2_TILE tile[PORT_I2S_ADC2_TILE_NUM]
#define PORT_I2S_ADC2_TILE_NUM 1
#define PORT_I2S_ADC3_TILE tile[PORT_I2S_ADC3_TILE_NUM]
#define PORT_I2S_ADC3_TILE_NUM 1
#define PORT_ADAT_OUT_TILE tile[PORT_ADAT_OUT_TILE_NUM]
#define PORT_ADAT_OUT_TILE_NUM 1
#define PORT_SPDIF_OUT_TILE tile[PORT_SPDIF_OUT_TILE_NUM]
#define PORT_SPDIF_OUT_TILE_NUM 1
#define PORT_MIDI_IN_TILE tile[PORT_MIDI_IN_TILE_NUM]
#define PORT_MIDI_IN_TILE_NUM 1
#define PORT_MIDI_OUT_TILE tile[PORT_MIDI_OUT_TILE_NUM]
#define PORT_MIDI_OUT_TILE_NUM 1

void xk_audio_316_mc_ab_init_ports();

#endif /* AUDIO_316_MC_AB_PORTS_H */

