// Copyright 2024 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.
#ifndef AUDIO_316_MC_AB_PORTS_H
#define AUDIO_316_MC_AB_PORTS_H

#include "../boards_utils.h"

#include <platform.h>  // for tile identifiers

#define PORT_SQI_CS BOARDS_PORT(0, 1B)
#define PORT_SQI_SCLK BOARDS_PORT(0, 1C)
#define PORT_SQI_SIO BOARDS_PORT(0, 4B)
#define PORT_CTRL BOARDS_PORT(0, 8D)
#define PORT_I2C_SCL BOARDS_PORT(0, 1L)
#define PORT_I2C_SDA BOARDS_PORT(0, 1M)
#define PORT_MCLK_COUNT BOARDS_PORT(0, 16B)
#define PORT_MCLK_IN_USB BOARDS_PORT(0, 1D)
#define PORT_PLL_REF BOARDS_PORT(0, 1A)
#define PORT_ADAT_IN BOARDS_PORT(0, 1O)
#define PORT_SPDIF_IN BOARDS_PORT(0, 1N)
#define PORT_MCLK_IN BOARDS_PORT(1, 1D)
#define PORT_MCLK_COUNT_2 BOARDS_PORT(1, 16B)
#define PORT_I2S_LRCLK BOARDS_PORT(1, 1B)
#define PORT_I2S_BCLK BOARDS_PORT(1, 1C)
#define PORT_I2S_DAC0 BOARDS_PORT(1, 1P)
#define PORT_I2S_DAC1 BOARDS_PORT(1, 1O)
#define PORT_I2S_DAC2 BOARDS_PORT(1, 1N)
#define PORT_I2S_DAC3 BOARDS_PORT(1, 1M)
#define PORT_I2S_ADC0 BOARDS_PORT(1, 1I)
#define PORT_I2S_ADC1 BOARDS_PORT(1, 1J)
#define PORT_I2S_ADC2 BOARDS_PORT(1, 1K)
#define PORT_I2S_ADC3 BOARDS_PORT(1, 1L)
#define PORT_ADAT_OUT BOARDS_PORT(1, 1G)
#define PORT_SPDIF_OUT BOARDS_PORT(1, 1A)
#define PORT_MIDI_IN BOARDS_PORT(1, 1F)
#define PORT_MIDI_OUT BOARDS_PORT(1, 4C)

void xk_audio_316_mc_ab_init_ports_0();

#endif /* AUDIO_316_MC_AB_PORTS_H */

